export class Districts {
  districts: Record<string, any> = {
    'Hà Nội': [
      'Đống Đa',
      'Cầu Giấy',
      'Nam Từ Liêm',
      'Long Biên',
      'Ba Đình',
      'Hoàn Kiếm',
      'Sóc Sơn',
      'Mê Linh',
      'Gia Lâm',
      'Bắc Từ Liêm',
      'Tây Hồ',
      'Hai Bà Trưng',
      'Đông Anh',
    ],
    'Hưng Yên': [
      'Kim Động',
      'Phù Cừ',
      'Khoái Châu',
      'Tiên Lữ',
      'Yên Mỹ',
      'Mỹ Hào',
      'Ân Thi',
      'Văn Giang',
      'TP Hưng Yên',
      'Văn Lâm',
    ],
    'Thái Bình': [
      'Kiến Xương',
      'Vũ Thư',
      'Đông Hưng',
      'TP Thái Bình',
      'Thái Thụy',
      'Quỳnh Phụ',
      'Tiền Hải',
      'Hưng Hà',
    ],
    'Hải Dương': [
      'Gia Lộc',
      'Kinh Môn',
      'Bình Ging',
      'Thanh Hà',
      'Cẩm Giàng',
      'Chí Linh',
      'Ninh Giang',
      'Thanh Miện',
      'Nam Sách',
      'Tứ Kỳ',
      'Kim Thành',
      'TP Hải Dương',
    ],
    'Thanh Hoá': [
      'Yên Đinh',
      'Nông Cống',
      'Như Xuân',
      'Hoằng Hoá',
      'Hà Trung',
      'Ngọc Lặc',
      'Thạch Thành',
      'Cẩm Thủy',
      'Triệu Sơn',
      'Thọ Xuân',
      'Nga Sơn',
      'Quan Hoá',
      'Thiệu Hoá',
      'Như Thanh',
      'Bá Thước',
      'Tĩnh Gia',
      'Quảng Xương',
      'Quan Sơn',
      'TP Thanh Hoá',
      'Lang Chánh',
      'Vĩnh Lộc',
      'Thường Xuân',
      'Bỉm Sơn',
      'Đông Sơn',
      'Hậu Lộc',
      'Sầm Sơn',
      'Mường Lát',
    ],
    'Nghệ An': [
      'Quỳnh Lưu',
      'Cửa Lò',
      'Quỳ Hợp',
      'Hưng Nguyên',
      'Tân Kỳ',
      'Yên Thành',
      'Hoàng Mai',
      'Quỳ Châu',
      'Tương Dương',
      'Quế Phong',
      'Nghi Lộc',
      'Nghĩa Đàn',
      'Nam Đàn',
      'Diễn Châu',
      'Kỳ Sơn',
      'Thái Hoà',
      'Anh Sơn',
      'Con Cuông',
      'Đô Lương',
      'Vinh',
      'Thanh Chương',
    ],
    'Quảng Bình': [
      'Lệ Thuỷ',
      'Quảng Trạch',
      'Bố Trạch',
      'Tuyên Hoá',
      'Quảng Ninh',
      'Đồng Hới',
      'Ba Đồn',
      'Minh Hoá',
    ],
    'Hà Tĩnh': [
      'Tx Kỳ Anh',
      'TP Hà Tĩnh',
      'Thạch Hà',
      'Đức Thọ',
      'Vũ Quang',
      'Hương Khê',
      'Cẩm Xuyên',
      'Nghi Xuân',
      'Lộc Hà',
      'Hương Sơn',
      'Kỳ Anh',
      'Hồng Lĩnh',
      'Can Lộc',
    ],
    'Bình Định': [
      'An Lão',
      'An Nhơn',
      'Hoài Ân',
      'Hoài Nhơn',
      'Phù Cát',
      'Phù Mỹ',
      'Quy Nhơn',
      'Tuy Phước',
      'Tây Sơn',
      'Vân Canh',
      'Vĩnh Thạnh',
    ],
    'Khánh Hòa': [
      'Cam Lâm',
      'Cam Ranh',
      'Diên Khánh',
      'Khánh Sơn',
      'Khánh Vĩnh',
      'Ninh Hòa',
      'Nha Trang',
      'Vạn Ninh',
      'Tp Nha Trang ',
      'Tp Cam Ranh',
      'TX Ninh Hòa',
    ],
    'Phú Yên': [
      'Đông Hòa',
      'Đồng Xuân',
      'Phú Hòa',
      'Tuy Hòa',
      'Sơn Hòa',
      'Sông Cầu',
      'Sông Hinh',
      'Tuy An',
      'Tây Hòa',
      'Tp Tuy Hòa',
    ],
    'Quảng Ngãi': [
      'Bình Sơn',
      'Ba Tơ',
      'Đức Phổ',
      'Lý Sơn',
      'Mộ Đức',
      'Minh Long',
      'Nghĩa Hành',
      'Quảng Ngãi',
      'Sơn Hà',
      'Sơn Tịnh',
      'Sơn Tây',
      'Trà Bồng',
      'Tư Nghĩa',
    ],
    'Quảng Trị': [
      'Cồn Cỏ',
      'Cam Lộ',
      'Đông Hà',
      'Đak Krông',
      'Gio Linh',
      'Hướng Hóa',
      'Hải Lăng',
      'Quảng Trị',
      'Triệu Phong',
      'Vĩnh Linh',
    ],
    'Cà Mau': [
      'Cà Mau',
      'Cái Nước',
      'Đầm Dơi',
      'Năm Căn',
      'Ngọc Hiển',
      'Phú Tân',
      'Thới Bình',
      'Trần Văn Thời',
      'U Minh',
    ],
  };
  public getDistrictsList(code: any) {
    return this.districts[code];
  }

  public getLength() {
    return Object.keys(this.districts).length;
  }
}
