export class Districts {
  districts: Record<string, any> = {
    'Hà Nội': [
      'Đống Đa',
      'Cầu Giấy',
      'Nam Từ Liêm',
      'Long Biên',
      'Ba Đình',
      'Hoàn Kiếm',
      'Sóc Sơn',
      'Mê Linh',
      'Gia Lâm',
      'Bắc Từ Liêm',
      'Tây Hồ',
      'Hai Bà Trưng',
      'Đông Anh',
    ],
    'Hưng Yên': [
      'Kim Động',
      'Phù Cừ',
      'Khoái Châu',
      'Tiên Lữ',
      'Yên Mỹ',
      'Mỹ Hào',
      'Ân Thi',
      'Văn Giang',
      'TP Hưng Yên',
      'Văn Lâm',
    ],
    'Thái Bình': [
      'Kiến Xương',
      'Vũ Thư',
      'Đông Hưng',
      'TP Thái Bình',
      'Thái Thụy',
      'Quỳnh Phụ',
      'Tiền Hải',
      'Hưng Hà',
    ],
    'Hải Dương': [
      'Gia Lộc',
      'Kinh Môn',
      'Bình Ging',
      'Thanh Hà',
      'Cẩm Giàng',
      'Chí Linh',
      'Ninh Giang',
      'Thanh Miện',
      'Nam Sách',
      'Tứ Kỳ',
      'Kim Thành',
      'TP Hải Dương',
    ],
    'Thanh Hoá': [
      'Yên Đinh',
      'Nông Cống',
      'Như Xuân',
      'Hoằng Hoá',
      'Hà Trung',
      'Ngọc Lặc',
      'Thạch Thành',
      'Cẩm Thủy',
      'Triệu Sơn',
      'Thọ Xuân',
      'Nga Sơn',
      'Quan Hoá',
      'Thiệu Hoá',
      'Như Thanh',
      'Bá Thước',
      'Tĩnh Gia',
      'Quảng Xương',
      'Quan Sơn',
      'TP Thanh Hoá',
      'Lang Chánh',
      'Vĩnh Lộc',
      'Thường Xuân',
      'Bỉm Sơn',
      'Đông Sơn',
      'Hậu Lộc',
      'Sầm Sơn',
      'Mường Lát',
    ],
    'Nghệ An': [
      'Quỳnh Lưu',
      'Cửa Lò',
      'Quỳ Hợp',
      'Hưng Nguyên',
      'Tân Kỳ',
      'Yên Thành',
      'Hoàng Mai',
      'Quỳ Châu',
      'Tương Dương',
      'Quế Phong',
      'Nghi Lộc',
      'Nghĩa Đàn',
      'Nam Đàn',
      'Diễn Châu',
      'Kỳ Sơn',
      'Thái Hoà',
      'Anh Sơn',
      'Con Cuông',
      'Đô Lương',
      'Vinh',
      'Thanh Chương',
    ],
    'Quảng Bình': [
      'Lệ Thuỷ',
      'Quảng Trạch',
      'Bố Trạch',
      'Tuyên Hoá',
      'Quảng Ninh',
      'Đồng Hới',
      'Ba Đồn',
      'Minh Hoá',
    ],
    'Hà Tĩnh': [
      'Tx Kỳ Anh',
      'TP Hà Tĩnh',
      'Thạch Hà',
      'Đức Thọ',
      'Vũ Quang',
      'Hương Khê',
      'Cẩm Xuyên',
      'Nghi Xuân',
      'Lộc Hà',
      'Hương Sơn',
      'Kỳ Anh',
      'Hồng Lĩnh',
      'Can Lộc',
    ],
  };
  public getDistrictsList(code: any) {
    return this.districts[code];
  }

  public getLength() {
    return Object.keys(this.districts).length;
  }
}
